name: .NET Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Framework
      run: |
        choco install dotnetfx --version=4.8.0  # تثبيت .NET Framework 4.8
    - name: Install dependencies
      run: nuget restore  # استخدام nuget لاستعادة الحزم
    - name: Build project
      run: msbuild /p:Configuration=Release  # استخدام msbuild للبناء
    - name: Run tests
      run: vstest.console <path-to-your-test-assembly>  # استخدم أمر مناسب لتشغيل الاختبارات
